### ISSUE TITLE
Invalid sample rate: 96000 Hz? 

### ISSUE THREAD

**Issue by cryoguy** [xnk/pacific-tpms#1]
Thanks for your efforts.  I am playing with your code and getting following error.  any thoughts?
`./tpmsrecv.py 
linux; GNU C++ version 7.2.1 20171224; Boost_106600; UHD_003.010.002.000-0-unknown

gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
Invalid sample rate: 96000 Hz
Traceback (most recent call last):
  File "./tpmsrecv.py", line 213, in <module>
    main()
  File "./tpmsrecv.py", line 208, in main
    tb = top_block_cls()
  File "./tpmsrecv.py", line 160, in __init__
    self.freq_xlating_fir_filter_xxx_0 = filter.freq_xlating_fir_filter_ccc(self.decim, (firdes.low_pass(1, throttle_rate, 180000, 20000, firdes.WIN_HAMMING, 6.76)), self.freqadj, throttle_rate)
  File "/usr/lib/python2.7/site-packages/gnuradio/filter/filter_swig.py", line 139, in low_pass
    return _filter_swig.firdes_low_pass(*args, **kwargs)
RuntimeError: firdes check failed: 0 < fa <= sampling_freq / 2
`

**Comment by xnk** [comment]
96kHz sounds strange. I'm requesting a 400kHz sample rate (throttle_rate=400000). Note that I only ran this on my HackRF. I have very little experience with the RTL sticks, will they only deal with very specific sample rates?
